/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_gnome_YelpService
#define DBUS_GLIB_CLIENT_WRAPPERS_org_gnome_YelpService

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_gnome_YelpService_new_window (DBusGProxy *proxy, const char * IN_url, const char * IN_timestamp, GError **error)

{
  return dbus_g_proxy_call (proxy, "new_window", error, G_TYPE_STRING, IN_url, G_TYPE_STRING, IN_timestamp, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_gnome_YelpService_new_window_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_gnome_YelpService_new_window_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_gnome_YelpService_new_window_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_gnome_YelpService_new_window_async (DBusGProxy *proxy, const char * IN_url, const char * IN_timestamp, org_gnome_YelpService_new_window_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "new_window", org_gnome_YelpService_new_window_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_url, G_TYPE_STRING, IN_timestamp, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_gnome_YelpService_get_url_list (DBusGProxy *proxy, char ** OUT_urls, GError **error)

{
  return dbus_g_proxy_call (proxy, "get_url_list", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_urls, G_TYPE_INVALID);
}

typedef void (*org_gnome_YelpService_get_url_list_reply) (DBusGProxy *proxy, char * OUT_urls, GError *error, gpointer userdata);

static void
org_gnome_YelpService_get_url_list_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_urls;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_urls, G_TYPE_INVALID);
  (*(org_gnome_YelpService_get_url_list_reply)data->cb) (proxy, OUT_urls, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_gnome_YelpService_get_url_list_async (DBusGProxy *proxy, org_gnome_YelpService_get_url_list_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "get_url_list", org_gnome_YelpService_get_url_list_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_gnome_YelpService */

G_END_DECLS
